const suggestionsDummy: Suggestion[] = 
  [
    {
      id: 1,
      imdbId: "tt4574334",
      thumbnail: "https://m.media-amazon.com/images/M/MV5BMDZkYmVhNjMtNWU4MC00MDQxLWE3MjYtZGMzZWI1ZjhlOWJmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
      name: "Stranger Things",
      streamingService: "Netflix",
      genre: "Drama, Fantasy, Horror",
      runtime: "43 min",
      rating: "8.7",
    },
    {
      id: 2,
      imdbId: "tt0903747",
      thumbnail: "https://m.media-amazon.com/images/M/MV5BNDkyZThhNmMtZDBjYS00NDBmLTlkMjgtNWM2ZWYzZDQxZWU1XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_SX300.jpg",
      name: "Breaking Bad",
      streamingService: "Netflix",
      genre: "Crime, Drama, Thriller",
      runtime: "45 min",
      rating: "9.5",
    },
    {
      id: 3,
      imdbId: "tt4158110",
      thumbnail: "https://m.media-amazon.com/images/M/MV5BM2QyNDIzOGMtNThhNS00NmUwLWI0ZjUtZjdkN2I1OTRjZWQ3XkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_SX300.jpg",
      name: "Mr. Robot",
      streamingService: "Netflix",
      genre: "Crime, Drama, Thriller",
      runtime: "60 min",
      rating: "8.6",
    },
    {
      id: 4,
      imdbId: "tt1439629",
      thumbnail: "https://m.media-amazon.com/images/M/MV5BNDQ5NDZiYjktZmFmMy00MjAxLTk1MDktOGZjYTY5YTE1ODdmXkEyXkFqcGdeQXVyNjcwMzEzMTU@._V1_SX300.jpg",
      name: "Community",
      streamingService: "Netflix",
      genre: "Comedy",
      runtime: "25 min",
      rating: "8.5",
    },
    {
      id: 5,
      imdbId: "tt3398228",
      thumbnail: "https://m.media-amazon.com/images/M/MV5BYWQwMDNkM2MtODU4OS00OTY3LTgwOTItNjE2Yzc0MzRkMDllXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
      name: "Bojack Horseman",
      streamingService: "Netflix",
      genre: "Animation, Comedy, Drama",
      runtime: "25 min",
      rating: "8.8",
    },
  ]

  export default suggestionsDummy